spring:
  application:
    name: micr-task

dubbo:
  scan:
    base-packages: com.bjpowernode.task
  registry:
    address: zookeepr://localhost:2181
  consumer:
    timeout: 50000
    check: false
    retries: 0